export const SRI_LANKA_CITIES = [
  // Western Province
  "Colombo",
  "Dehiwala-Mount Lavinia",
  "Moratuwa",
  "Sri Jayawardenepura Kotte",
  "Negombo",
  "Kesbewa",
  "Maharagama",
  "Kotte",
  "Homagama",
  "Kaduwela",
  "Kelaniya",
  "Wattala",
  "Ragama",
  "Gampaha",
  "Ja-Ela",
  "Kandana",
  "Katunayake",
  "Minuwangoda",
  "Kiribathgoda",
  "Peliyagoda",
  "Ragama",
  "Seeduwa",
  "Nittambuwa",
  "Kalutara",
  "Panadura",
  "Horana",
  "Beruwala",
  "Aluthgama",
  "Matugama",
  "Wadduwa",
  // Central Province
  "Kandy",
  "Gampola",
  "Nawalapitiya",
  "Peradeniya",
  "Katugastota",
  "Akurana",
  "Matale",
  "Dambulla",
  "Rattota",
  "Nuwara Eliya",
  "Hatton",
  "Talawakele",
  "Bandarawela",
  "Badulla",
  // Southern Province
  "Galle",
  "Hikkaduwa",
  "Ambalangoda",
  "Elpitiya",
  "Bentota",
  "Karapitiya",
  "Matara",
  "Weligama",
  "Dikwella",
  "Akuressa",
  "Hambantota",
  "Tangalle",
  "Tissamaharama",
  // Northern Province
  "Jaffna",
  "Chavakachcheri",
  "Point Pedro",
  "Nallur",
  "Kilinochchi",
  "Mannar",
  "Vavuniya",
  "Mullaitivu",
  // Eastern Province
  "Trincomalee",
  "Kinniya",
  "Kantale",
  "Batticaloa",
  "Eravur",
  "Kalmunai",
  "Akkaraipattu",
  "Ampara",
  // North Western Province
  "Kurunegala",
  "Kuliyapitiya",
  "Pannala",
  "Wariyapola",
  "Mawathagama",
  "Puttalam",
  "Chilaw",
  "Wennappuwa",
  "Nattandiya",
  // North Central Province
  "Anuradhapura",
  "Kekirawa",
  "Eppawala",
  "Polonnaruwa",
  "Kaduruwela",
  "Medirigiriya",
  // Uva Province
  "Badulla",
  "Bandarawela",
  "Haputale",
  "Monaragala",
  "Wellawaya",
  "Bibile",
  // Sabaragamuwa Province
  "Ratnapura",
  "Kuruwita",
  "Pelmadulla",
  "Embilipitiya",
  "Balangoda",
  "Kegalle",
  "Mawanella",
  "Warakapola",
  "Ruwanwella",
];
